<a href="https://colab.research.google.com/github/mihail1707/dap-2024/blob/main/les03/lab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторная работа №3. NumPy

## Задание

Выполните следующие задания:

1. Откройте в файл в Google Colab (используйте собственный форк репозитория).
2. Решите задачи.
3. Сохраните результат в ваш репозиторий github в директорию ./les03
4. Создайте pull request в репозиторий https://github.com/chebotarevsa/dap-2024. Название pull request должно иметь формат "<Номер лабораторной работы>  <Номер группы> <ФИО>"
5. Сдайте работу в системе "Пегас", в отчет укажите ссылку на pull request

In [ ]:
import numpy as np
np.version.version

'2.1.0'

1. Создать массив 10x10 со случайными значениями, найти минимум и максимум (низкая)

In [13]:
# Напишите ваш код здесь
import numpy as np
y = np.random.random((10, 10))
# y = np.random.randint(0, 20, (10, 10))
print(y)
print("min: ",y.min())
print("max: ",y.max())

[[0.0998621  0.49010944 0.87617984 0.99981432 0.40276559 0.32062531
  0.90759344 0.02742981 0.83569407 0.9250137 ]
 [0.29951961 0.09904848 0.29543744 0.533837   0.36135553 0.23628466
  0.33924841 0.14030078 0.32382976 0.11803696]
 [0.80449836 0.53234264 0.12640174 0.00613866 0.15131903 0.10321463
  0.09647872 0.50905058 0.11306466 0.11991843]
 [0.72485736 0.6758781  0.08742183 0.13028249 0.73003053 0.33463214
  0.78791409 0.7220399  0.03386874 0.35124886]
 [0.09919666 0.11396209 0.28800195 0.83793952 0.27426459 0.05250473
  0.96279037 0.25585486 0.6667666  0.29061451]
 [0.36905408 0.26105466 0.54618066 0.96426098 0.90786833 0.03839908
  0.37294929 0.65004853 0.22220736 0.70714712]
 [0.35682408 0.8555574  0.4586099  0.57058808 0.48689056 0.37423946
  0.90382538 0.32717775 0.05035422 0.06844811]
 [0.8456828  0.26053815 0.51238924 0.72361639 0.38211297 0.79799583
  0.85537741 0.96347101 0.18253645 0.73648557]
 [0.02825014 0.01549492 0.27590105 0.70828302 0.06666628 0.62066057
  0.44692811

2. Создать 8x8 матрицу и заполнить её единицами и нулями в шахматном порядке

In [60]:
# Напишите ваш код здесь
m = np.zeros((8, 8))
m[::-2, ::2] = 1
m[::2, ::-2] = 1
print(m)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


3. Дан массив из 11 элементов, поменять знак у элементов, значения которых между 3 и 8

In [70]:
z = np.arange(11)
# Напишите ваш код здесь
z[3:8] *=  -1
print(z)

[ 0  1  2 -3 -4 -5 -6 -7  8  9 10]


4. Найти среднее заначение строки матрицы и вычесть его из каждого елемента строки

In [86]:
# z = np.random.rand(5, 10)
z= np.zeros((8, 8))
# Напишите ваш код здесь
z[:, :] = 1
print(z)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


5. Поменяйте 1 и 2 строки матрицы

In [99]:
z = np.arange(25).reshape(5,5)
# Напишите ваш код здесь
a = z[:1, :].copy()
z[:1, :] = z[1:2, :]
z[1:2, :] = a
print(z)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


6. Дан массив 10x2 подеставлющий собой точки в декартовой системе координат, преобразовать в полярную

In [105]:
z = np.random.random((10,2))
# Ваш код здесь
x,y = m[:,0], m[:,1]
r = np.hypot(x,y)
t = np.arctan2(y,x)
print(r)
print(t)

[1. 1. 1. 1. 1. 1. 1. 1.]
[1.57079633 0.         1.57079633 0.         1.57079633 0.
 1.57079633 0.        ]


7. Заменить максимальный элемент массива на ноль

In [104]:
z = np.random.random(10)
# Ваш код здесь
z[z.argmax()] = 0
print(z)

[0.76338113 0.79027104 0.         0.82653033 0.5461002  0.09261746
 0.34407128 0.13414835 0.46241467 0.22109002]


8. Дан массив, добавить 1 к каждому элементу с индексом, заданным в другом массиве. Добавление производиться только 1 раз

In [126]:
z = np.ones(10)
i = np.random.randint(0,len(z),20)
# Напишите ваш код здесь
z[list(set(i))]+=1
print(z)
print(list(set(i)))

[2. 2. 1. 2. 2. 2. 2. 1. 2. 2.]
[0, 1, 3, 4, 5, 6, 8, 9]


9. Дан вектор [1, 2, 3, 4, 5], построить новый вектор с тремя нулями между каждым значением

In [166]:
z = np.array([1,2,3,4,5])
# Напишите ваш код здесь
numZeros= 3
zNew = np.zeros(len(z) + (len(z)-1)*(numZeros))
zNew[::numZeros+1] = z
print(zNew)


5
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


10. Найти ближайшее к заданному значению число в заданном массиве

In [170]:
z = np.arange(100) # Число
v = np.random.uniform(0,100) # Массив
# Напишите ваш код здесь
numRound = np.round(v)
print('numNearest: ',z.searchsorted(numRound))
print("num : ",v)
print("arr : ",z)

numNearest:  65
num :  65.11956868638012
arr :  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


## Вопросы




**1**. Какой тип (dtype) будут иметь элементы массива?
``` python
np.array([1, 4, 2, 5, 3])
np.array([1., 4, 2, 5, 3])
np.array([1, 4, 2, 5, 3], dtype='float128')
np.array([1., 4, 2, 5, 3], dtype='complex128')
np.array([1, 4, 2, 5, 3], dtype ='float64')
np.array([1, 4, 2, 5, 3], dtype =int64)
np.array([1, 4, 2, 5, 3], dtype='bool')
np.array([1, 4, 2, 5, 3], dtype='str')
np.array([1, 4, 2, 5, '3'])
np.array([1, -4, 2, 0, 1j])
```

**2**. Что будет выведено в консоль и почему?
``` python
np.array([1, 4, 2, 5, 3], dtype='str')[1] + '1'
np.array([1, -4, 2, 0, 3], dtype='bool')[3] or np.array([1, -4, 2, 0, 3])[1]
np.array([1, -4, 2, 0, 3], dtype='bool')[3] and np.array([1, -4, 2, 0, 3])[1]
np.array([1, -4, 2, 0, True], dtype='int64')[-1]
np.array([1, -4, 2, 0, 1j], dtype='int64')[1]
np.array([1, -4, 2, 0, 1j], dtype='str')[-1]
np.array([1, 4, 2, 5, '3'])[-1] * 3
```

**3**. Каков результат операции?

``` python
np.ones((3, 5), dtype=float)
np.full((3, 5), 3.14)
np.linspace(0, 1, 5)
np.diag((1,3,5))
np.smile((1,3,5))
np.random.random((3, 3))
np.eye(3)
np.empty(3)
```



**4**. Дан двумерный массив X, что будет выведено в консоль?

``` python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])
```

``` python
X[0,0]
X[-1,-1]
X[0:1,-1]
X[0:2,-1]
X[0:2,0:2]
X[1,1:3]
X[1,:]
X[1,:]
X[:,:]
X[:]
X[::2,::2]
X[0:3:2,0:3:2]
X[::-1,::-1]
```

**5**. Дан двумерный массив grid, в чем различее между операциями?


``` python
grid = np.arange(16).reshape((4, 4))
```

``` python
np.split(grid, [2])
np.split(grid, [2], axis=1)
```


**6**. В чем различие между операциями?

``` python
    [1, 2, 3] + [3, 2, 1]
    np.array([1, 2, 3]) + np.array([3, 2, 1])
```

**7**. Как в CodeLab измерить время выполнения кода?

**8**. Дан массив X, каковы результаты операций?

```python
X = np.array([[3, 5, 2, 4],
      [7, 6, 8, 8],
      [1, 6, 7, 7]])

np.sum(M)
np.sum(M, axis=1)
np.sum(M, axis=0)
np.sum(M, axis=2)
np.sum(M, 1)
sum(M)
sum(M,1)
```

**9**. Дан массив X, что будет выведено в консоль?

```python
X = np.array([1,2,3,4])

X > 3
X < 3
X[X < 3]
X[X > 3]
X[X != 3]
```

**10**.  В чем преимущество массивов NumPy по сравнению с обычными списками.  Чем обусловлено это преимущество?